### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by xuiqzy** [gkotian/gautam_linux#24]
Could you please add a FLOSS license to at least the scripts directory?
You can also just choose a license in the Github Web Interface as far as i know and a LICENSE file is added to the top directory. (Optimally, a short license notice should be at the beginning of each file.)

**Comment by gkotian** [comment]
Thanks for opening this issue. Tbh, I never gave a serious thought to adding a license file. Will do it soon.

**Comment by gkotian** [comment]
After reading through https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633, I think the BSD 3 clause license is what I'm going to go with.

**Comment by xuiqzy** [comment]
Thank you very much for taking the time to choose and apply a license and releasing your work under a free and libre license! :)

To make easier and clearer for people seeing your code that they can reuse it, you can slowly introduce a license text at the beginning of files, my personal suggestion would be starting to paste it in the scripts.
Slightly modified from the link you used and with your personal info from the `LICENSE` file:
```
Copyright (c) 2019, Gautam Kotian
All rights reserved.

This source code is licensed under the 3-clause BSD license (BSD-new) found in the
LICENSE file in the root directory of this source tree. 
```
